<?php

// <editor-fold defaultstate="collapsed" desc="generic test preparation">
date_default_timezone_set('Europe/Paris');
// include tested class
$testedClass = preg_replace(
	array(
		'#\\.tests\\\\#',
		'#Test(?=.php$)#'
	)
	, ""
	, __FILE__
);
include $testedClass;
// </editor-fold>

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-15 at 00:31:09.
 */
class CsvParserTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var CsvParser
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$order = explode(',',  "-,group_name,sex,age_min_max,region,-,invites_no");
		$this->object = new CsvParser(__DIR__.'\profile.csv', $order);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * Basic parseRow test.
	 * @covers CsvParser::parseRow
	 * @todo   Implement testParseRow().
	 */
	public function testParseRow()
	{
		$this->object->order = array('name', 'age');
		$data = array('test', '1');
		$row = $this->object->parseRow($data);
		var_export($row);
		$this->assertEquals($row['columns']['name'], 'test');
		$this->assertEquals($row['columns']['age'], '1');
		$this->assertEquals($row['state'], CsvRowState::OK);
	}
}
